require 'minting/money_attribute/version'
require 'minting/money_attribute/core_ext'
require 'minting/money_attribute/railtie'
require 'minting/money_attribute/money_attribute'
require 'minting/money_attribute/money_type'
